name: Test
on:
    push:
        branches: [main]
    pull_request:
permissions:
    contents: read # to fetch code (actions/checkout)

jobs:
    Unit:
        runs-on: ${{ matrix.os }}
        timeout-minutes: 15
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
                node-version: [18, 20, 22]
                react-version: [18, 19]
                exclude:
                    # Reduce matrix size by excluding some combinations
                    - os: windows-latest
                      node-version: 20
                    - os: windows-latest
                      node-version: 22
                    - os: macOS-latest
                      node-version: 20
                    - os: macOS-latest
                      node-version: 22
        steps:
            - uses: actions/checkout@v5
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - run: pnpm i
            # Install specific React version based on the matrix
            - name: Install React ${{ matrix.react-version }}
              run: |
                  pnpm add -D react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }} react-test-renderer@${{ matrix.react-version }}
            - run: pnpm unit
              env:
                  CI: true
    Lint:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v5
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm
            - run: 'pnpm i && pnpm lint'
    Typecheck:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v5
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm
            - run: 'pnpm i && pnpm tsc'
