name: Test
on:
    push:
        branches: [main]
    pull_request:
permissions:
    contents: read # to fetch code (actions/checkout)

jobs:
    Tests:
        runs-on: ${{ matrix.os }}
        timeout-minutes: 15
        strategy:
            matrix:
                include:
                    - node-version: 16
                      os: ubuntu-latest
                      react-version: 16
                    - node-version: 16
                      os: windows-latest
                      react-version: 16
                    - node-version: 16
                      os: macOS-latest
                      react-version: 16
                    - node-version: 18
                      os: ubuntu-latest
                      react-version: 17
                    - node-version: 20
                      os: ubuntu-latest
                      react-version: 18
                    - node-version: 20
                      os: ubuntu-latest
                      react-version: 'latest'
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - name: Install dependencies with specific React version
              run: |
                pnpm i
                pnpm remove react react-dom
                pnpm add react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }} --save-peer
            - run: pnpm test
              env:
                  CI: true
    # ...existing code...